### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by niranjanchavadi** [erinata/smart-save#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [smart-save](https://github.com/erinata/smart-save) package 0.6.1

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\asus\.atom\packages\smart-save\lib\smart-save.js:15

ReferenceError: path is not defined
    at Object.savePath (/packages/smart-save/lib/smart-save.js:15:24)
    at /packages/smart-save/lib/smart-save.js:64:80
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:424586)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:44778)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1215561)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:446919)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:455763)
    at Pane.activateItem (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:457933)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1165207)
```

### Commands

```
     -4:43.9.0 editor:auto-indent (input.hidden-input)
     -4:33.2.0 editor:move-line-down (input.hidden-input)
     -4:25.2.0 editor:move-line-up (input.hidden-input)
     -4:09.2.0 encoding-selector:show (input.hidden-input)
     -3:55.1.0 editor:move-selection-left (input.hidden-input)
     -3:50.6.0 editor:move-selection-right (input.hidden-input)
     -3:43.8.0 encoding-selector:show (input.hidden-input)
     -3:32.8.0 pane:split-up-and-copy-active-item (input.hidden-input)
     -3:06.3.0 window:focus-next-pane (atom-pane.pane.active)
     -2:57.8.0 editor:toggle-soft-wrap (atom-pane.pane.active)
  2x -2:52.5.0 editor:fold-at-indent-level-1 (atom-pane.pane.active)
     -2:34.7.0 editor:unfold-current-row (input.hidden-input)
     -2:23.9.0 editor:fold-at-indent-level-9 (input.hidden-input)
     -2:08.9.0 atom-beautify:beautify-editor (input.hidden-input)
     -1:47.8.0 atom-beautify:open-settings (input.hidden-input)
  2x -1:09.3.0 format-shell:format (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
format-shell 2.2.1 
save-hooks 1.0.3 
smart-save 0.6.1 
```

**Comment by ChaseYang** [comment]
just delete the unexpected code can solve the problem,but the filename will not be auto filled。
![Image](https://user-images.githubusercontent.com/47837695/118749547-4f4a4180-b890-11eb-88f2-12ae8fdcf47b.png)

see your file path on your error report  : C:\Users\asus\.atom\packages\smart-save\lib\smart-save.js:15 @niranjanchavadi
