### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by mr-rean** [erinata/smart-save#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [smart-save](https://github.com/erinata/smart-save) package 0.6.1

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\Raihan\.atom\packages\smart-save\lib\smart-save.js:15

ReferenceError: path is not defined
    at Object.savePath (/packages/smart-save/lib/smart-save.js:15:24)
    at /packages/smart-save/lib/smart-save.js:64:80
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1211760)
    at Emitter.emit (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1213201)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:424681)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:14:44396)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1211760)
    at Emitter.emit (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1213201)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:447014)
    at Pane.setActiveItem (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:455858)
    at Pane.activateItem (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:458028)
    at TabBarView.onClick (~/AppData/Local/atom/app-1.42.0/resources/app/static/<embedded>:11:1162847)
```

### Commands

```
  2x -4:59.3.0 core:undo (input.hidden-input)
     -4:57.2.0 core:cut (input.hidden-input)
     -4:57.2.0 core:copy (input.hidden-input)
     -4:51.8.0 snippets:next-tab-stop (input.hidden-input)
     -4:51.8.0 snippets:expand (input.hidden-input)
     -4:51.8.0 editor:indent (input.hidden-input)
  2x -4:50.6.0 core:paste (input.hidden-input)
     -4:46.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -4:45.7.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  2x -4:43.7.0 core:undo (input.hidden-input)
     -4:42.1.0 core:cut (input.hidden-input)
  7x -4:38.3.0 core:undo (input.hidden-input)
     -4:35 core:paste (input.hidden-input)
     -3:58.9.0 core:confirm (input.hidden-input)
  2x -3:40.9.0 autosave-onchange:toggle (input.hidden-input)
     -2:58 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-idle-autosave 0.3.0 
atom-live-server 2.3.0 
atom-live-server-plus 3.0.1 
autosave-onchange 1.5.1 
smart-save 0.6.1 
timed-autosave 1.2.0 
```

**Comment by ChaseYang** [comment]
just delete the unexpected code can solve the problem,but the filename will not be auto filled。
![Image](https://user-images.githubusercontent.com/47837695/118750146-735a5280-b891-11eb-912c-a3db996790a9.png)

see your file path on your error report : C:\Users\asus.atom\packages\smart-save\lib\smart-save.js:15 @mr-rean
